### ISSUE TITLE
Requires docker as container engine

### ISSUE THREAD

**Issue by c2bo** [oceanprotocol/operator-service#24]
The implementation actively looks for the presence of /.dockerenv to figure out if the service is running in a container.
This file does not exist in container engines other than docker and especially when deploying to kubernetes, docker should not be assumed imho.

https://github.com/oceanprotocol/operator-service/blob/061e6b07f928f1ed6d1401e3cfef8a089c9f4dad/operator_service/kubernetes_api.py#L9

https://github.com/oceanprotocol/operator-service/blob/061e6b07f928f1ed6d1401e3cfef8a089c9f4dad/operator_service/routes.py#L23

A quick and dirty fix could be an adjustment to the deployment.yaml with a poststart script, e.g.
```
lifecycle:
    postStart:
        exec:
            command: ["/bin/sh", "-c", "touch /.dockerenv"]
```
In the long run, the implementation should probably be adjusted and check for some kind of environment variable, 
either a self-created environment variable, or standard k8s one like KUBERNETES_SERVICE_HOST (https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#environment-variables)

**Comment by mihaisc** [comment]
closing stale issue
