### ISSUE TITLE
Write admin route unit tests. Improve operator route unit tests

### ISSUE THREAD

**Issue by MantisClone** [oceanprotocol/operator-service#34]
The Operator Service is missing unit tests for admin routes:
https://github.com/oceanprotocol/operator-service/blob/main/test/test_admin.py

- [ ] Write admin route unit tests

Improve existing operator unit tests.  During recent changes (#33) it was discovered that basic syntax errors in the error responses were not caught by existing unit tests - indicating that the unit tests should be improved.

- [ ] Improve operator route unit tests

**Comment by DMats** [comment]
@alexcos20 Per our discussion earlier this week, I am assigning this issue to myself.  CC @AnaLoznianu

**Comment by mihaisc** [comment]
stale issue
