### ISSUE TITLE
Clear and consistent progression of status and returned metadata

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/operator-service#6]
Currently, when a job is `/init`, the /info endpoint first returns some of the workflow JSON object (but in a different structure, with extra attribs...). 

The returned JSON has i.e. 2 'metadata' attributes. More meaningful names would enhance readability. 

Next, after repeated /info requests, the JSON returned includes a new 'status' attribute. This status endpoint should include a clear progression of the status of the job, and also be included from the start. 
job received -> configure pod requisitioned / started / completed -> (same for algo and publish pods) -> etc...

**Comment by alexcos20** [comment]
Will use /status endpoint to get status information
