### ISSUE TITLE
Write a script to test the routes of the operator service

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/operator-service#60]
The existent tests are very old. Use them as inspiration but not rely on them.

**Comment by LoznianuAnamaria** [comment]
As the old tests are not relevant anymore, let's delete them and start from scratch

**Comment by calina-c** [comment]
@AnaLoznianu I'm a bit confused. Didn't I add tests months ago? Why is this still open?

**Comment by LoznianuAnamaria** [comment]
That's a good question. We missed to close the ticket
