### ISSUE TITLE
Do not publish results if the algorithm fails

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/operator-service#7]
Currently, the 'publish' pod is called and publishes the results of the algorithm, even if the algorithm has an error, and the results are therefore useless. This behavior can be updated to save resources. One option can be to have the user control the publishing of the results based on their own opinion (after checking the logs of the 'algorithm' pod). Another option can be to have the results published if the algorithm actually succeeds, based on a process return code of 0.

**Comment by alexcos20** [comment]
Publishing will be done at user's request, using the UI (Commons)
